### ISSUE TITLE
Crash on startup - Mod Loading has failed

### ISSUE THREAD

**Issue by TYPyz** [TheCBProject/CBMultipart#102]
A user of my modpack reported this crash to me.
I am not an expert and therefore I cannot understand the reason for the crash. It says it's caused by CB Multipart so I thought reporting it to here was the best thing to do.
He is unable to play the modpack due to this crash that occurs every time he try to start it
[crash-2021-09-09_11.07.13-fml.txt](https://github.com/TheCBProject/CBMultipart/files/7138387/crash-2021-09-09_11.07.13-fml.txt)

**Comment by covers1624** [comment]
You are attempting to run the game on Java16, this is not supported. You will need to use java 15 maximum.
