### ISSUE TITLE
Crash on Java versions above 11. Java's latest long term support version is 17.

### ISSUE THREAD

**Issue by RVOtakuMike** [TheCBProject/CBMultipart#106]
Just wanted to bring this to your attention, have a good day!

Crash log: https://pastebin.com/pHgGpqBF

**Comment by RyzenFromFire** [comment]
Can confirm this issue is present. Running Java 16, CBMultipart loads on Java 8. Haven't tested 11.

**Comment by covers1624** [comment]
Java 16 and above are not supported.
