### ISSUE TITLE
Chisel microblocks support for 1.16.5

### ISSUE THREAD

**Issue by WDomss** [TheCBProject/CBMultipart#107]
Will the mod support Chisel for making microblocks? I tried to follow the tutorial here but I think it is not working anymore because I've looked everywhere in my config folder, and I cannot configure the CB Multipart to support Chisel.

**Comment by WDomss** [comment]
That's great to hear! Good luck with working on this project.

**Comment by covers1624** [comment]
Support for mods adding micro materials via Inter mods messages has been added for the next pending release.

Information for this can be found on the wiki: https://github.com/TheCBProject/CBMultipart/wiki/Micro-materials#adding-micro-materials

**Comment by covers1624** [comment]
Support for IMC messages has been added in `3.0.3.121` (CurseForge Approval pending).
