### ISSUE TITLE
Crash on Mac M1

### ISSUE THREAD

**Issue by gildiarz** [TheCBProject/CBMultipart#109]
Hello, I discovered that on a Macbook M1 this mod causes an mc loading error. Without this mod (and dependent mods) the problem does not occur. On windows this problem is absent. Modpack FTB OceanBlock.
Below crash log:
https://paste.ee/p/eQeTi

**Comment by covers1624** [comment]
Java 16 is not supported. You will need to use Java 8 - 15.

**Comment by gildiarz** [comment]
Tested with Java 15, working with no problems. Thanks!
