### ISSUE TITLE
saw should be destroyed when durability runs out

### ISSUE THREAD

**Issue by Sunekaer** [TheCBProject/CBMultipart#111]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/174

CBMultipart-1.16.5-3.0.2.120-universal.jar

**Comment by covers1624** [comment]
This issue has been resolved in a pending future release.

**Comment by covers1624** [comment]
This issue should be resolved in `3.0.3.121` (CurseForge approval pending).
