### ISSUE TITLE
95% of items missing in survival mode. 

### ISSUE THREAD

**Issue by djoveryde** [TheCBProject/CBMultipart#113]
I am having a really weird issue where in create you can see all the microblocks available but in survival 95% of them are missing when searching for CB Microblock items.

Running 1.16.5 minecraft, latest CB version

**Comment by covers1624** [comment]
By default, CBMultipart will hide all Micro blocks except Stone from JEI. They exist in the Vanilla creative tab and are craftable.

I will leave this issue open as it appears the Config option for this is currently non functional.

**Comment by covers1624** [comment]
The issue with the `showAllMicroblocks` config option not functioning have been resolved in the next pending release.

**Comment by covers1624** [comment]
This issue should be resolved in `3.0.3.121` (CurseForge approval pending).
