### ISSUE TITLE
config file to add blocks

### ISSUE THREAD

**Issue by skicek** [TheCBProject/CBMultipart#115]
Hi,

Old versions had microblock.cfg file in which we could add blocks that can be used to create microblocks. Now I see that ConfigContent.scala is mostly commented out. Do you plan to rewrite it and allow again to add blocks to the list? Speaking about mc 1.16.5 and above

Thanks,

**Comment by covers1624** [comment]
The config option for this currently doesn't exist. A replacement is being looked into.
