### ISSUE TITLE
Error Loading Mods (Failed to load mod)

### ISSUE THREAD

**Issue by ilovehans10** [TheCBProject/CBMultipart#116]
I was trying to play the Oceanblock modpack and I have made no modifications to the default modpack and I have deep reinstalled three times. I have no other information other than the fact that the mod crashes a minute or so into loading and removing the mod and its dependencies allows the game to fully launch. I can provide extra info if needed but this is what I have for now. 

[https://pastebin.com/ZaSpCd5c](https://pastebin.com/ZaSpCd5c)

**Comment by Illuxxium** [comment]
I had the same problem with CBMultipart on OpenJDK 16 on Manjaro Linux. Downgrading to OpenJDK 11 fixed it for me on Oceanblock.

Hope this helps!

**Comment by covers1624** [comment]
Java 16 and above are not supported.

Use java 8-15
