### ISSUE TITLE
I don't see the custom-micromaterials.cfg

### ISSUE THREAD

**Issue by pikachu99** [TheCBProject/CBMultipart#118]
I am wanting to have modded blocks as micro blocks, but I don't see the config file that is stated on the wiki page.
MC version: 1.16.5
Mod version:  3.0.2.120
Forge version: 36.2.4

**Comment by covers1624** [comment]
The config file mentioned on the wiki is not in a released version just yet.

Please track this issue for updates: https://github.com/TheCBProject/CBMultipart/issues/99
