### ISSUE TITLE
Website button in Minecraft Mods screen links to wrong destination

### ISSUE THREAD

**Issue by NotFitForPurpose** [TheCBProject/CBMultipart#119]
The "Website" button in the Mods screen takes you to Github:
  https://github.com/TheCBProject/CBMultipart
Should take you to Curseforge:
  https://www.curseforge.com/minecraft/mc-mods/cb-multipart
where the Jar file lives.

Minecraft tile screen
> Mods button
  > "mods with updates" tick-box
    > CBMultipart
      > Website button

**Comment by covers1624** [comment]
This issue has been resolved in the latest release.
