### ISSUE TITLE
When I'm using Arclight(forge/bukkit server core) to launch the All the mods6 It crashed

### ISSUE THREAD

**Issue by QingShuiMuYang** [TheCBProject/CBMultipart#121]
Here's what Arclight's author asked me to send you.(some details)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module

**Comment by covers1624** [comment]
Java 16 is not supported. Use Java 15.
