### ISSUE TITLE
Mod wont load when trying to launch modpack

### ISSUE THREAD

**Issue by JJ0236** [TheCBProject/CBMultipart#123]
hey so ive been trying to launch the above and beyond modpack and its saying this mod will not load here is the crash report

[crash report.txt](https://github.com/TheCBProject/CBMultipart/files/7700006/crash.report.txt)

**Comment by Spielepapagei** [comment]
I have the same problem

[crash-2021-12-13_16.52.14-fml.txt](https://github.com/TheCBProject/CBMultipart/files/7705094/crash-2021-12-13_16.52.14-fml.txt)
!

**Comment by covers1624** [comment]
Java 16 and 17 are not supported.

Please use the Java version shipped with Minecraft. Java 8. Or Java 15 maximum.
