### ISSUE TITLE
Error Loading Mods *2 Errors have occurred during loading!!

### ISSUE THREAD

**Issue by F4rozen** [TheCBProject/CBMultipart#127]
Failed to Load Mod (Not mentioned which mod)
<img width="1440" alt="Screenshot 2022-01-19 at 10 38 50 AM" src="https://user-images.githubusercontent.com/98006399/150067867-b01c3699-ddcf-41fc-b586-55a9bdea3cac.png">
[crash-2022-01-19_10.32.47-fml.txt](https://github.com/TheCBProject/CBMultipart/files/7894241/crash-2022-01-19_10.32.47-fml.txt)

**Comment by covers1624** [comment]
Java 17 is not supported. Use Java 8 to 15 maximum.

This has been reported a thousand times. Please double-check closed issues for future reports :)
