### ISSUE TITLE
Crash after placing a hollow crafting table slab

### ISSUE THREAD

**Issue by Catomax262** [TheCBProject/CBMultipart#132]
Crash report: https://pastebin.com/eRichHaS

This mod's been very suspicious, it could cause Minecraft to crash at any moment.

**Comment by Catomax262** [comment]
Also, i don't remember which mod NEEDED this to work.

**Comment by covers1624** [comment]
This particular crash was fixed long ago in CodeChickenLib.

You will need to update your mods.
