### ISSUE TITLE
No in-game recipes 1.16.5

### ISSUE THREAD

**Issue by Puket123** [TheCBProject/CBMultipart#133]
Cannot craft any of the blocks.

**Comment by covers1624** [comment]
Recipes absolutely exist, however, do not show up in JEI correctly.

Place a saw in a crafting table and try putting a block next to it.

Most modded blocks will not work, unless they have explicitly enabled support.

Most vanilla full blocks are supported by default.

**Comment by knacky34** [comment]
Hello,
I can't craft any blocks either. Try with the three available saw and few vanilla blocks like dirt, cobble, oak planks, stone.
