### ISSUE TITLE
Potential Mod loading error

### ISSUE THREAD

**Issue by StalkerM8** [TheCBProject/CBMultipart#134]
Hello,
I have been having some trouble getting a recent modpack to work correctly, and my little knowledge of how to read a crash log points to this mod being the issue. I've tried a prior version (Which is what these logs show) and the newer one and the pack still will load through like normal but the moment its supposed to be showing the title screen, its a crash which shows these 2 logs, "Open Mods folder". And a screen simply saying "Failed to load mod". Doesn't even specify (see attached image). 

Any help or pointers to this are greatly appreciated. 
V/r 

[crash-2022-05-21_13.54.28-fml.txt](https://github.com/TheCBProject/CBMultipart/files/8748276/crash-2022-05-21_13.54.28-fml.txt)
[latest.log](https://github.com/TheCBProject/CBMultipart/files/8748277/latest.log)
![javaw_2022-05-21_14-05-13](https://user-images.githubusercontent.com/24470093/169667360-54dda11b-57ab-497c-9d1f-db444b70b3f3.png)

**Comment by Kilian-Jugie** [comment]
Hello,
I had the exact same thing here... Any news on this ? Having two different crashes with same issue might help

[crash-2022-05-27_10.48.35-fml.txt](https://github.com/TheCBProject/CBMultipart/files/8785394/crash-2022-05-27_10.48.35-fml.txt)
[latest.log](https://github.com/TheCBProject/CBMultipart/files/8785398/latest.log)

**Comment by RapidFuge** [comment]
Any fixes? I also have the same issue

**Comment by covers1624** [comment]
@StalkerM8  `Java Version: 17.0.1, Oracle Corporation`
@Kilian-Jugie `Java Version: 16.0.2, Oracle Corporation`

Java 17 and Java 16 are not supported by CBMultipart for 1.16. The only officially supported version is Java 8, however, should work up to java 15.
