### ISSUE TITLE
CB Multipart failed to load.

### ISSUE THREAD

**Issue by NotEvenBelow** [TheCBProject/CBMultipart#136]
[crash-2022-07-16_17.47.48-fml.txt](https://github.com/TheCBProject/CBMultipart/files/9125600/crash-2022-07-16_17.47.48-fml.txt)

- Version:
CBMultipart-1.16.5-3.0.4.123-universal
CodeChickenLib-1.16.5-4.0.7.445-universal
Scorge-3.1.3

**Comment by covers1624** [comment]
Java 16 is not supported.

Use java 8-15.
