### ISSUE TITLE
Is there going to be a CBMultipart 1.18.2 Version ? 

### ISSUE THREAD

**Issue by Luke1550** [TheCBProject/CBMultipart#137]
Hello There, 
i was asking myself if there is going to be a CBMultipart 1.18.2 Version . 
Thank you for Developing this : ) 
Luke

**Comment by Luke1550** [comment]
Sorry Didnt see it on Curseforge

**Comment by Luke1550** [comment]
Sorry for the irretation , i'd love if youd make a 1.18.2 version of this mod

**Comment by covers1624** [comment]
This is in the works.

There is no ETA.
