### ISSUE TITLE
solve CB Multipart failed to load. 

### ISSUE THREAD

**Issue by NothingToHere** [TheCBProject/CBMultipart#138]
If you are using java17, add the following parameters to JVM arguments:
`--add-opens java.base/java.lang=ALL-UNNAMED`

**Comment by covers1624** [comment]
Java 17 is not supported. Please do not open frivolous issues.

**Comment by theoparis** [comment]
Why is this closed along with every other issue? I don't see why Java 17 and 19 can't be supported and I don't see an open issue to track progress on fixing it.

**Comment by covers1624** [comment]
Minecraft 1.16 is not supported. Development has moved to Minecraft 1.18+, which does not contain this bug.

**Comment by theoparis** [comment]
Sorry - my bad. I was already using Java 17 with 1.18.2 but it seems to have resolved itself somehow 😂 I guess I must have done something wrong. Luckily, the modpack works now.
