### ISSUE TITLE
crash every time I attempt to open a world that seems to implicate multiple mods

### ISSUE THREAD

**Issue by veccyboi** [TheCBProject/CBMultipart#141]
a while ago, I downloaded cbmultipart as well as a few other library mods (scorge and codechickelib) because I wanted to play with project red. up until now, it has never caused any issues.

recently, I installed this mod: [https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport](url), and now, every time I open a world, the game crashes, despite the game itself initially loading perfectly fine. the crash report mentioned not only these two mods, but other mods like supplementaries that have never crashed with cbmultipart before. I think it unlikely that the caves and cliffs backport mod is the cause because it doesn't seem to change too much other than add 1.17 features to 1.16.5.

prior to this, i updated project red and all dependencies, including cbmultipart, to their latest versions. i also got deleted what i hope was the right config file (CBMicroblock.cfg)

since this mod seemed to be mentioned a lot in the crash report, I am posting this issue here.

tech information:
minecraft version: 1.16.5
forge version: 36.2.2
mods folder:
![image](https://user-images.githubusercontent.com/85643556/188514746-05e04eb3-a154-4a6a-bca6-3228cd48c6fb.png)
my config folder (sorted alphabetically, all "c" files):
![image](https://user-images.githubusercontent.com/85643556/188514836-39ea31bf-6988-4a19-a0c2-19cf87ef5e61.png)
crash report: https://pastebin.com/e9nwFcu7

**Comment by covers1624** [comment]
Remove Baritone. Hacked clients are not supported.
