### ISSUE TITLE
Minecraft 1.18.* support

### ISSUE THREAD

**Issue by creeloper27** [TheCBProject/CBMultipart#142]
Hi, I was wondering if there are plans to support 1.18.* minecraft versions.

**Comment by Adrikikicp** [comment]
Scorge (scala support for Forge) is not available to minecraft 1.18.*

**Comment by covers1624** [comment]
Scala will not be used going forward.

We are absolutely done with it. It was a mistake to begin with.

1.18 is in the works.

Do not ask for ETA's.
