### ISSUE TITLE
[Idea] The ability to add new blocks to microblocks

### ISSUE THREAD

**Issue by Mleekush** [TheCBProject/CBMultipart#152]
Sorry if this is already a feature, but I've searched where I could and didn't find anything.
The idea is: In the config file, you could list blocks from other mods that you could turn into microblocs. Just use the original block data, like textures and hardness.
I know the original ForgeMultipart had this and I would love to have it here too.
If it's possible, please implement it all the way to the oldest versions so everybody can use it.

**Comment by covers1624** [comment]
You can do this via the `microblocks.cfg` file in your configs folder.

Please note: this config will need to be manually synced to clients.
