### ISSUE TITLE
v3.1.1 release?

### ISSUE THREAD

**Issue by doctorbmw** [TheCBProject/CBMultipart#153]
not sure if this is the correct spot to ask if and when version 3.1.1 is getting released?  i updated project red today and the game is telling me i need cbmultipart 3.1.1 and cb micro blocks 3.1.1 tp load the game.

**Comment by doctorbmw** [comment]
when i tried to roll back to the previous versions of project red they are no longer available  on curse forge

**Comment by covers1624** [comment]
I was not aware this had not been released.

It is now on CurseForge.
