### ISSUE TITLE
Scorge?

### ISSUE THREAD

**Issue by Notlucky101** [TheCBProject/CBMultipart#154]
Do I need scorge? I currently running minecraft 1.19.2. There is not support from scorge for this version. If not then I do not have the recipes to craft anything. Before you ask I have download code chicken lib

**Comment by ThisIsSP4RTAN** [comment]
> Do I need scorge? I currently running minecraft 1.19.2. There is not support from scorge for this version. If not then I do not have the recipes to craft anything. Before you ask I have download code chicken lib

Recipes for the Microblocks? You have to use the top left crafting squares and the recipes don't show up in jei 
![image](https://github.com/TheCBProject/CBMultipart/assets/61633596/7dc9b5ec-8f1b-4218-bb20-d8b98746c616)
![image](https://github.com/TheCBProject/CBMultipart/assets/61633596/43ff2058-63db-4d97-8c10-d50c2c9c0b4c)

**Comment by Notlucky101** [comment]
thx I will try that...

**Comment by Notlucky101** [comment]
So I tried it and it worked, however only on vanilla blocks. Would be nice
on any block like blue skies stone brick

**Comment by covers1624** [comment]
Scorge is not required on 1.18 and above. CBM is entirely written in Java now.
