### ISSUE TITLE
Translocators requires CB Multipart on 1.20.1 but it's not available for that version.

### ISSUE THREAD

**Issue by Gbergz** [TheCBProject/CBMultipart#160]
Title.

![ss](https://github.com/TheCBProject/CBMultipart/assets/26634554/44b0da07-e691-4361-88c3-beecbdcc60b2)

**Comment by sous-park** [comment]
> Title.

https://modrinth.com/mod/cb-multipart/version/3.3.0.143

**Comment by Gbergz** [comment]
@sous-park Thanks, but it's needed on CurseForge if mod is to be used in modpacks. Not updated there yet.

**Comment by covers1624** [comment]
I had some breakage with my new deployment stuff. Had to upload things manually. I thought i uploaded multipart...

**Comment by covers1624** [comment]
![Screenshot_20240427-182541](https://github.com/TheCBProject/CBMultipart/assets/1369578/ee02e845-7f08-46fc-af33-144076a8343a)
It appears to be under manual review. For whatever reason.

**Comment by Gbergz** [comment]
Ah gotcha, no worries.

**Comment by covers1624** [comment]
You have my permission to ship as an override mod until its approved.

**Comment by Gbergz** [comment]
Thanks! 
Then hopefully CurseForge will still approve it while in the overrides folder. Had experiences where they dont unfortunately.

**Comment by covers1624** [comment]
If they give you strife, point them here for reference to permission to ship. I'll contact them tomorrow some time about why its under manual review.

**Comment by Gbergz** [comment]
Will do and thanks.

**Comment by Gbergz** [comment]
It's now available, but the newest update (v3.3.0.144) doesn't boot on Forge anymore.

But v3.3.0.143 does. Thought I'd mention that.

Crash-report: https://gist.githubusercontent.com/Gbergz/f78d577fc70decd6222099c63ae32896/raw/e4038ea607a577e2364bad7bc7624dd2b0ba538e/gistfile1.txt

**Comment by covers1624** [comment]
CurseForge approved the files.

As for the issues with 144 not booting. 145 should resolve this.
