### ISSUE TITLE
Incompatible with Cleanroom

### ISSUE THREAD

**Issue by roidrole** [TheCBProject/CBMultipart#166]
Crashes on startup when loading with CleanroomMC

Loaded mods : 
- Minecraft 1.12.2
- Cleanroom 0.2.2-alpha
- CodeChicken Lib 3.2.3.358
- CBMultipart 2.6.2.83
- Fugue 0.15.8
- Scalar 3.4.2

Everything is on default config

[latest.log](https://mclo.gs/pI0tGKh)

**Comment by covers1624** [comment]
1.12.2 is not supported, third party forks of Forge are also not supported.
