### ISSUE TITLE
Angelica mod issue

### ISSUE THREAD

**Issue by Biskupsky** [TheCBProject/CBMultipart#167]
Hi !
In Angelica (sodium for 1.7.10) there is said "CodeChicken[Core]<1.2.0 - Threading issues, use 1.2.0+"
I currently use mechanism mod, that automaticlly downloads ForgeMultipart 1.7.10-1.2.0.345. After putting it into 1.7.10 folder in mods game crashes: 
"escription: There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler"

Looks like ForgeMultiPart contains CodeChickenCore that is older than 1.2.0 ? Is the link in mod outdated or what ? Help pls

**Comment by covers1624** [comment]
1.7.10 is not supported anymore.

CCC on startup should be automatically downloading CodeChickenLib.

Please try manually adding CCL: https://maven.covers1624.net/repository/maven-hosted/codechicken/CodeChickenLib/1.7.10-1.1.3.141/CodeChickenLib-1.7.10-1.1.3.141-universal.jar
