### ISSUE TITLE
[Forge MultiPart CBE] Some blocks are not placeable on upside-down slabs/panels/covers

### ISSUE THREAD

**Issue by phlopsi** [TheCBProject/CBMultipart#51]
Manually triggered debug crash: https://pastebin.com/6QzuMU8C

The following blocks can be placed on vanilla upside-down slabs, but not on FMP blocks:
- Stone Pressure Plate
- Wooden Pressure Plate
- Weighted Pressure Plate (Light)
- Weighted Pressure Plate (Heavy)
- Pumpkin
- Jack o'Lantern
- Bed
- Redstone
- Redstone Repeater
- Redstone Comparator
- Flower Pot

**Comment by covers1624** [comment]
This should be resolved in 1.16+
