### ISSUE TITLE
Thermal Foundation`s cover conflicts with the multipart, which causes the renderer to only red and crash

### ISSUE THREAD

**Issue by kerocate** [TheCBProject/CBMultipart#63]
My version of Minecraft is 1.12.2. All mods are up to date with the latest ones. When the cover appears on the hand, it will crash, which makes me have to delete the cover of Te in the player's inventory NBT to enter the world.

**Comment by covers1624** [comment]
Can you please provide a crash log?

**Comment by covers1624** [comment]
No crash report was provided, Unfortunately, 1.12 is no longer supported.
