### ISSUE TITLE
Weird placement bug (video included)

### ISSUE THREAD

**Issue by ItsMeZioh** [TheCBProject/CBMultipart#65]
anyone know what is causing this?

https://youtu.be/b-rVkichVz0

**Comment by ItsMeZioh** [comment]
More info: Its only in my server, i have no shaders on, i restarted my game and reinstalled.

**Comment by seancrain** [comment]
I've been getting this as well. I will test it on singleplayer in a few minutes.

**Comment by ItsMeZioh** [comment]
do you host with catserver by chance?

**Comment by seancrain** [comment]
No. My server is home hosted. My modpack, however, contains the latest release of FMP from the ChickenBones Maven page, which was released on August 6.

The previous build came out on January 17. Something was altered in the newest release that caused this. I would roll back the version to the January 17 build if you need to use it a lot for building until they fix it.

**Comment by ItsMeZioh** [comment]
thanks man. i will give it a try

**Comment by covers1624** [comment]
Interesting.. im not sure what would cause that.. what is your floor made of?

**Comment by covers1624** [comment]
Unfortunately, 1.12 is no longer supported.
