### ISSUE TITLE
Crash at start of custom modpack

### ISSUE THREAD

**Issue by Imrald** [TheCBProject/CBMultipart#66]
When i launch my custom made modpack the game crashes at start giving me this crash report

https://pastebin.com/DN7A4AGD

I'm a noob of these type of things, can anyone help me to see what the problem is?
Thanks
Hoping i'm doing the right way

**Comment by covers1624** [comment]
A mod in your Modpack was class loading classes transformed by FMP before it could transform them.

At any rate, 1.12 is no longer supported.
