### ISSUE TITLE
Nor Gate - Fails to Render (Ghost Entity).

### ISSUE THREAD

**Issue by Danekjovax** [TheCBProject/CBMultipart#69]
Version Info:
modpack-Dungeons Dragons & Space Shuttles v.6.3
forge-1.12.2-14.23.5.2807-universal
ForgeMultipart-1.12.2-2.6.2.83-universal

The NOR gate fails to render on-screen much of the time, and when it is "invisible", it will act like a ghost block (like it was mined but server-side has the block as unmined), and make it hard to walk over/around. Notably, the hitbox for the gate is also non-existant, and only breaking the underlying block will force it to "pop" and go into your inventory. Replacing the gate will allow it to render as normal, but something as yet undetermined causes it to stop rendering again (relogging, chunk unload/reload, etc).

Screenshots attached. Thanks!
Before...
![2019-10-26_23 16 24](https://user-images.githubusercontent.com/10191173/67629090-9ce30180-f847-11e9-9e16-7bf2074c7af1.png)

After breaking underlying block and replacing it...
![2019-10-26_23 17 03](https://user-images.githubusercontent.com/10191173/67629091-9f455b80-f847-11e9-8f19-88d980a0cde4.png)

**Comment by Danekjovax** [comment]
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/441

**Comment by covers1624** [comment]
Unfortunately, 1.12 is no longer supported.

If you encounter this or a similar issue in 1.16 please create a new issue.
