### ISSUE TITLE
Microblocks Doesn't Have In-Game Recipes

### ISSUE THREAD

**Issue by kmccmk9** [TheCBProject/CBMultipart#78]
I noticed that with the latest release, I can no longer craft the microblocks. For example I've included a screenshot, I would expect this to turn into a slab? I noticed some stones and some woods seem to work as expected. But not all blocks seem to respect the recipe. And  yes I have checked the creative menu that slab and covers, etc. of many of these blocks do exist but are not craftable.

![image](https://user-images.githubusercontent.com/678335/78465673-9eea9f80-76c6-11ea-9371-384a347bc576.png)

**Comment by ThanEEpic** [comment]
Yeah I'm having this problem too with version 1.12.2-2.6.2.83.

**Comment by DrakenRolle** [comment]
Same with 1.12.2-2.6.2.83

**Comment by covers1624** [comment]
1.12 is unfortunately not supported anymore.

Please create a new issue if this is still a problem in 1.16+
