### ISSUE TITLE
Startup Crash with ForgeMultipartCBE

### ISSUE THREAD

**Issue by Mysticpasta1** [TheCBProject/CBMultipart#82]
I'm working on a 1.12.2 modpack that needs CBE to work with thing like project red and wireless CBE, can you please help fix this or if you can't help me find a working version of CBE that work on 1.12.2 2748 forge. Here is my gist --> https://gist.github.com/Mysticpasta1/653fded6a2c433f67f27a5cfc8cb704a :)

**Comment by Mysticpasta1** [comment]
Btw my discord is Hauntedpasta1#8200 is you want to talk there :)

**Comment by covers1624** [comment]
Unfortunately, 1.12 is not supported anymore.

However, I recommend double-checking you don't have a duplicate version of FMP in your mods folder.

**Comment by Mysticpasta1** [comment]
I checked for duplicates of FMP in my mods folder there were none. So either the mod isn't working and I need a different version for 1.12.2 or the mod as to be fixed. :)

**Comment by Mysticpasta1** [comment]
Is there a recommended version of FMP
