### ISSUE TITLE
java.lang.IllegalArgumentException on trying to break cobblestone cover

### ISSUE THREAD

**Issue by Monniasza** [TheCBProject/CBMultipart#83]
I can't properly break the cobblestone cover using an emerald pickaxe from Actually Additions. I think that pickaxe is not an issue
Crash report: [log](https://paste.ee/p/aYdp8)
Mod version:  2.6.2.83

The location, where the cover used to be is now an invalid block and can't be passed.
When it is pushed by a piston, it becomes valid, but any attempt to break it causes crash

**Comment by covers1624** [comment]
The crash report no longer exists.

Additionally, 1.12 is not supported anymore.

If this is still an issue in 1.16+ please create a new issue.
