### ISSUE TITLE
Blocks sometimes drop when they are quickly broken in creative

### ISSUE THREAD

**Issue by Rayzeq** [TheCBProject/CBMultipart#84]
Here is a video

https://user-images.githubusercontent.com/26172375/118007014-0c4a1480-b34c-11eb-9fa4-00eda482725e.mp4

**Comment by covers1624** [comment]
This is due to a ray trace miss. You have hit the block, but when FMP goes to see which part you have hit, it has not found the part. As a fallback, FMP will drop all parts in the space.

There's not much that can be done here.
