### ISSUE TITLE
Reflection error with Java 16

### ISSUE THREAD

**Issue by Hojosa** [TheCBProject/CBMultipart#96]
Version Info:
forge-1.16.5-36.1.32
CodeChickenLib-1.16.5-4.0.2.427
CBMultipart-1.16.5-3.0.2.119

When using Java 16, a refelection error occures resulting in a crash at startup: (does not happen, when using java 11 or 8)
[crash-2021-07-18_19.49.48-fml.txt](https://github.com/TheCBProject/CBMultipart/files/6836723/crash-2021-07-18_19.49.48-fml.txt)

**Comment by covers1624** [comment]
Minecraft 1.16 is not java 16 ready. Use Java15.
