### ISSUE TITLE
Being inside of certain non-solid blocks allows for placement of partial blocks behind the player

### ISSUE THREAD

**Issue by muzikbike** [TheCBProject/CBMultipart#98]
![2021-07-20_21 28 57](https://user-images.githubusercontent.com/52297970/126391242-da5e11ff-f5fd-4dc1-93b1-f4ef4aa2df6a.png)
![2021-07-20_21 28 59](https://user-images.githubusercontent.com/52297970/126391248-89608b86-d6f1-4e4e-8832-508c4301c50e.png)

**Comment by covers1624** [comment]
This will not be fixed, this is not a bug.
