### ISSUE TITLE
Documentation for adding modded blocks

### ISSUE THREAD

**Issue by TylerBourne** [TheCBProject/CBMultipart#99]
I'm trying to add support for modded blocks.  I haven't been able to find clear documentation on how to set up config files to add additional blocks.  I tried the old method of adding a microblocks.cfg to config but it didn't work.  If that method should still work the same please let me know and close this issue.

**Comment by covers1624** [comment]
I have created a wiki article on this topic here on GitHub: https://github.com/TheCBProject/CBMultipart/wiki/Micro-materials#adding-micro-materials

**Comment by covers1624** [comment]
The config has been revived as of `3.0.3.121` (CurseForge approval pending).

Please see the previously linked wiki article for usage.
